
name: Build Cython Banded Solver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install cython numpy wheel setuptools

      - name: Build Cython extension
        run: |
          python setup.py build_ext --inplace
          dir

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cython-banded
          path: "*.pyd"
